pipeline {
    agent any 
    options {
        ansiColor('xterm')
    }
    environment {
        MAVEN_OPTS = '-Djansi.force=true'
    }
    stages {
        stage('Build') { 
            steps {
		        sh 'curl -u admin:password http://172.16.101.15:8081/artifactory/wso2-keystore/QA/wso2carbon.jks -o wso2carbon.jks'
		        sh './gradlew buildWSO2 --stacktrace'
            }
        }
		stage('Deploy') { 
            steps {
                sh './gradlew deployLocal'
            }
        }
       stage('Test') { 
            steps {
                sh 'newman run ./test/collection/collection.json -e ./test/collection/Dev_environment.json --insecure'
            }
        }     

        stage('Deploy snapshot') { 
            steps {
                withCredentials([steps.usernamePassword(
      credentialsId: 'ARTIFACTORY',
      usernameVariable: 'USERNAME',
      passwordVariable: 'PASSWORD')]) {
                    echo 'USERNAME : '+ USERNAME
                    echo 'PASSWORD: '+ PASSWORD
                    sh './gradlew deploySnapshot'
                }
            }
        }
       
    }
}
