pipeline {
    agent any 
    options {
        ansiColor('xterm')
    }
    environment {
        MAVEN_OPTS = '-Djansi.force=true'
    }
    stages {
        stage('Build') { 
            steps {
		        sh 'curl -u admin:password http://172.16.101.15:8081/artifactory/wso2-keystore/QA/wso2carbon.jks -o wso2carbon.jks'
		        sh './gradlew buildWSO2 --stacktrace'
            }
        }
		stage('Deploy') { 
            steps {
                sh './gradlew deployLocal'
            }
        }
       stage('Test') { 
            steps {
                sh './gradlew testWSO2'
            }
        }        // TODO: testing stage should go here
        stage('Deploy snapshot') { 
            steps {
                withCredentials([steps.usernamePassword(
      credentialsId: 'ARTIFACTORY',
      usernameVariable: 'JFROG_USERNAME',
      passwordVariable: 'JFROG_PASSWORD')]) {
                    sh './gradlew deploySnapshot'
                }
            }
        }
       
    }
}
